### ISSUE TITLE
Test results

### ISSUE THREAD

**Issue by meitalbensinai** [pilehvar/ADW#2]
Hi,
Great project!
When I run the test "testWeightedOverlap" the assertions fail.. (for example - expected:<0.6346> but was:<0.5735252906982333>)
I wondered if the problem is with my configuration or something else..
Thanks!

**Comment by meitalbensinai** [comment]
And another small question:
When using your demo site, it gives me the answer in now time, but while running it from Eclipse it takes for ever (around 9 seconds)
Do you have any idea why? @pilehvar

**Comment by pilehvar** [comment]
Hi Meital,

Thank you for pointing out this issue; I just fixed it. 
The issue was for the change we recently made to the way Weighted Overlap is being calculated.

For your second question, the ADWTest takes some 7-8 secs on my machine to run; how long does it take on yours? There are two ways to speed up similarity measurement: use Cosine instead of Weighted Overlap or go for smaller vector sizes (replace testedVectorSize=0 in the adw.properties file to say 1000).

-Taher

**Comment by meitalbensinai** [comment]
Oh, thanks for the quick respond!
The test is super fast actually, around 4-5 secs!
I guess that the problem comes up when dealing with "long" texts (6-7 sentences).
Do you recommend to use it when dealing with such cases? Or maybe it would be better to use it just for short texts (let's say 1 sentence) and different method for longer ones? @pilehvar

**Comment by pilehvar** [comment]
In fact for such long textual items the disambiguation step is not that helpful. So, you might want to change that to NONE to further speed up.

**Comment by meitalbensinai** [comment]
Thanks! I'll check it out.
Again, great project (and paper), love it!
